# Hydrogen

spacing         = 2
padding         = 0
hide_ascii      = false
prefer_small_ascii = true
separator       = "→"
key_color       = "Cyan"
separator_color = "White"

[palette]
glyph = ""
type = "Full"
visible = true

[bar]
glyph           = "▪"
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = false
visible         = false

[box]
border          = "rounded"
visible         = false

[box.inner_margin]
x               = 1
y               = 0

[custom_ascii]
color = "Blue"
path = "~/.config/macchina/themes/ascii.txt"

[randomize]
key_color       = false
separator_color = false

[keys]
host            = "Host"
kernel          = "Kernel"
battery         = "Battery"
os              = "OS"
de              = "DE"
wm              = "WM"
distro          = "Distro"
terminal        = "Terminal"
shell           = "Shell"
packages        = "Packages"
uptime          = "Uptime"
memory          = "Memory"
machine         = "Machine"
local_ip        = "Local IP"
backlight       = "Brightness"
resolution      = "Resolution"
cpu_load        = "CPU Load"
cpu             = "CPU"
